name: 'Build Website'

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Run a one-line script
        run: "build-website"
